//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KartaViewSharp.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KartaViewSharp.Tests.JsonResources", typeof(JsonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;status&quot;:{&quot;apiCode&quot;:600,&quot;apiMessage&quot;:&quot;The request has been processed without incidents&quot;,&quot;httpCode&quot;:200,&quot;httpMessage&quot;:&quot;Success&quot;},&quot;result&quot;:{&quot;data&quot;:[{&quot;address&quot;:&quot;7 Waverley Road, Lara Victoria 3212, Australia&quot;,&quot;appVersion&quot;:&quot;4.9.1 2&quot;,&quot;blurBuild&quot;:&quot;0&quot;,&quot;blurVersion&quot;:&quot;v1&quot;,&quot;cameraParameters&quot;:{&quot;fLen&quot;:5.0999999999999996,&quot;aperture&quot;:1.6000000238418579,&quot;hFoV&quot;:67.096040000000002,&quot;vFoV&quot;:52.884028865180774},&quot;clientTotal&quot;:&quot;4395&quot;,&quot;countActivePhotos&quot;:&quot;484&quot;,&quot;countMetadataPhotos&quot;:&quot;484&quot;,&quot;countMetadataVideos&quot;:&quot;10&quot;,&quot;countryCode&quot;:&quot;A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestRetrieveSequences {
            get {
                return ResourceManager.GetString("TestRetrieveSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;status&quot;:{&quot;apiCode&quot;:600,&quot;apiMessage&quot;:&quot;The request has been processed without incidents&quot;,&quot;httpCode&quot;:200,&quot;httpMessage&quot;:&quot;Success&quot;},&quot;result&quot;:{&quot;data&quot;:[{&quot;address&quot;:&quot;7 Waverley Road, Lara Victoria 3212, Australia&quot;,&quot;appVersion&quot;:&quot;4.9.1 2&quot;,&quot;blurBuild&quot;:&quot;0&quot;,&quot;blurVersion&quot;:&quot;v1&quot;,&quot;cameraParameters&quot;:{&quot;fLen&quot;:5.0999999999999996,&quot;aperture&quot;:1.6000000238418579,&quot;hFoV&quot;:67.096040000000002,&quot;vFoV&quot;:52.884028865180774},&quot;clientTotal&quot;:&quot;4395&quot;,&quot;countActivePhotos&quot;:&quot;484&quot;,&quot;countMetadataPhotos&quot;:&quot;484&quot;,&quot;countMetadataVideos&quot;:&quot;10&quot;,&quot;countryCode&quot;:&quot;A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestRetrieveSequencesWithPhoto {
            get {
                return ResourceManager.GetString("TestRetrieveSequencesWithPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;status&quot;:{&quot;apiCode&quot;:600,&quot;apiMessage&quot;:&quot;The request has been processed without incidents&quot;,&quot;httpCode&quot;:200,&quot;httpMessage&quot;:&quot;Success&quot;},&quot;result&quot;:{&quot;data&quot;:{&quot;0&quot;:{&quot;id&quot;:&quot;7068281&quot;,&quot;userId&quot;:&quot;304&quot;,&quot;address&quot;:&quot;7 Waverley Road, Lara Victoria 3212, Australia&quot;,&quot;appVersion&quot;:&quot;4.9.1 2&quot;,&quot;blurBuild&quot;:&quot;0&quot;,&quot;blurVersion&quot;:&quot;v1&quot;,&quot;cameraParameters&quot;:{&quot;fLen&quot;:5.0999999999999996,&quot;aperture&quot;:1.6000000238418579,&quot;hFoV&quot;:67.096040000000002,&quot;vFoV&quot;:52.884028865180774},&quot;clientTotal&quot;:&quot;4395&quot;,&quot;countActivePhotos&quot;:&quot;484&quot;,&quot;countMetadataPhotos&quot;:&quot;484&quot;,&quot;countMet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestRetrieveSequencesWithPhotos {
            get {
                return ResourceManager.GetString("TestRetrieveSequencesWithPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;status&quot;:{&quot;apiCode&quot;:600,&quot;apiMessage&quot;:&quot;The request has been processed without incidents&quot;,&quot;httpCode&quot;:200,&quot;httpMessage&quot;:&quot;Success&quot;},&quot;result&quot;:{&quot;data&quot;:[{&quot;address&quot;:&quot;7 Waverley Road, Lara Victoria 3212, Australia&quot;,&quot;appVersion&quot;:&quot;4.9.1 2&quot;,&quot;blurBuild&quot;:&quot;0&quot;,&quot;blurVersion&quot;:&quot;v1&quot;,&quot;cameraParameters&quot;:{&quot;fLen&quot;:5.0999999999999996,&quot;aperture&quot;:1.6000000238418579,&quot;hFoV&quot;:67.096040000000002,&quot;vFoV&quot;:52.884028865180774},&quot;clientTotal&quot;:&quot;4395&quot;,&quot;countActivePhotos&quot;:&quot;484&quot;,&quot;countMetadataPhotos&quot;:&quot;484&quot;,&quot;countMetadataVideos&quot;:&quot;10&quot;,&quot;countryCode&quot;:&quot;A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestRetrieveSequencesWithUser {
            get {
                return ResourceManager.GetString("TestRetrieveSequencesWithUser", resourceCulture);
            }
        }
    }
}
